"""Add client_id and plan_id to RadiusSession

Revision ID: 4a1e28c72b8c
Revises: cba61f0d8488
Create Date: 2025-08-28 11:11:56.745466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a1e28c72b8c'
down_revision = 'cba61f0d8488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('radius_session', sa.Column('client_id', sa.Integer(), nullable=False))
    op.add_column('radius_session', sa.Column('plan_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_radius_session_client_id', 'radius_session', 'client', ['client_id'], ['id'])
    op.create_foreign_key('fk_radius_session_plan_id', 'radius_session', 'plan', ['plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_radius_session_plan_id', 'radius_session', type_='foreignkey')
    op.drop_constraint('fk_radius_session_client_id', 'radius_session', type_='foreignkey')
    op.drop_column('radius_session', 'plan_id')
    op.drop_column('radius_session', 'client_id')
    # ### end Alembic commands ###
